# Default values for GBIF Spark application for process data and prepare map tiles.
# Name of the application, chart uses the name to find the .jar file.
appName: "gbif-ingest"
# Repository and tag for finding the image if selfhosted.
image:
  repository: ""
  tag: ""

# Stackable tag to use for the Spark application.
stackTag: 3.3.0-stackable23.1.0
# Spark running mode, currently only cluster is supported.
mode: cluster
# Main class for starting the Spark process.
appClass: org.gbif.pipelines.ingest.pipelines.VerbatimToIdentifierPipeline

# Ressource configuration for spark driver.
driver:
  # Number of cores for the Spark driver.
  core: "2000m"
  # Memory for the Spark driver.
  mem: "2Gi"

# Ressource configuration for spark executors.
executor:
  # Number of cores for each executor.
  core: "4000m"
  # Memory for each executor.
  mem: "8Gi"
  # Number of executors.
  instances: 3

nameOverride: ""
fullnameOverride: ""

#Mode for installing. This is a implemtantion for selecting which objects to install.
## all: Installs both spark application and configmaps
## config: Installs the configmaps maps into a namespace
## app: Installs the spark application
# The use case is for enabling templating only the application for use in Airflows or start an instance of spark within necessary updating the configsmaps
installMode: all

hdfs:
  # Name of the Stackabl HdfsCluster in the namespace.
  clusterName: gbif-hdfs