apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: {{ include "airflow-cluster.name" . }}
spec:
  version: {{ default .Chart.AppVersion .Values.stackTag }}
  statsdExporterVersion: v{{ .Values.statsdVersion }}
  executor: {{ .Values.executor }}
  loadExamples: {{ .Values.examples }}
  exposeConfig: {{ .Values.exposeConfigs }}
  credentialsSecret: {{ include "airflow-cluster.name" . }}-credentials
  volumes:
    - name: external-dags
      persistentVolumeClaim:
        claimName: {{ include "airflow-cluster.name" .}}-dag
        readOnly: true
  volumeMounts:
    - name: external-dags
      mountPath: /stackable/external-dags
  webservers:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__CORE__DAGS_FOLDER: "/stackable/external-dags"
          AIRFLOW_CONN_KUBERNETES_IN_CLUSTER: "kubernetes://?__extra__=%7B%22extra__kubernetes__in_cluster%22%3A+true%2C+%22extra__kubernetes__kube_config%22%3A+%22%22%2C+%22extra__kubernetes__kube_config_path%22%3A+%22%22%2C+%22extra__kubernetes__namespace%22%3A+%22%22%7D"
        replicas: {{ .Values.nodes.webservers.replicas }}
  workers:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__CORE__DAGS_FOLDER: "/stackable/external-dags"
          AIRFLOW_CONN_KUBERNETES_IN_CLUSTER: "kubernetes://?__extra__=%7B%22extra__kubernetes__in_cluster%22%3A+true%2C+%22extra__kubernetes__kube_config%22%3A+%22%22%2C+%22extra__kubernetes__kube_config_path%22%3A+%22%22%2C+%22extra__kubernetes__namespace%22%3A+%22%22%7D"
        replicas: {{ .Values.nodes.workers.replicas }}
  schedulers:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__CORE__DAGS_FOLDER: "/stackable/external-dags"
          AIRFLOW_CONN_KUBERNETES_IN_CLUSTER: "kubernetes://?__extra__=%7B%22extra__kubernetes__in_cluster%22%3A+true%2C+%22extra__kubernetes__kube_config%22%3A+%22%22%2C+%22extra__kubernetes__kube_config_path%22%3A+%22%22%2C+%22extra__kubernetes__namespace%22%3A+%22%22%7D"
        replicas: {{ .Values.nodes.schedulers.replicas }}