apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-dag
  labels:
    gbif-app: airflow-dags-containers
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: nfs-client
  resources:
    requests: 
      storage: {{ .Values.storageCapacity }}