# Define any nodes within the below named template to merge into the general template.
# This chart specific named template has precedence over the general template
# Be aware that the whole node gets overwritten
{{- define "gridded-datasets.sparkapplication" -}}

{{- end -}}

{{- if or (eq (lower .Values.installMode) "all") (eq (lower .Values.installMode) "app")  -}}
{{- include "gbif-chart-lib.sparkapplication" (list . "gridded-datasets.sparkapplication") -}}
{{- end -}}
