apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-custom
  namespace: {{ .Release.Namespace }}
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>hive.metastore.uris</name>
        {{- if .Values.thriftUrl }}
        <value>{{ .Values.thriftUrl }}</value>
        {{- else }}
        <value>thrift://{{ include "gbif-chart-lib.name" . }}-metastore-default-0.{{ include "gbif-chart-lib.name" . }}-metastore-default.{{ .Release.Namespace }}.svc.cluster.local:9083</value>
        {{- end }}
      </property>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>{{ .Values.warehouse }}</value>
      </property>
    </configuration>