apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
{{ include "gbif-chart-lib.stackableImage" . | indent 4 }}
  clusterConfig:
{{- if .Values.logging.enabled  }}     
    vectorAggregatorConfigMapName: {{ .Values.logging.discoveryMap }}
{{- end }}
    listenerClass: {{ .Values.listenerClass }}
    hdfs:
      configMap: {{ .Values.hdfsClusterName }}
    database:
      connString: jdbc:postgresql://{{ .Values.hiveDB.name }}/{{ .Values.hiveDB.db}}
      user: {{ .Values.hiveDB.user }}
      password: {{ .Values.hiveDB.password }}
      dbType: postgres
  metastore:
{{- if .Values.yunikorn.enabled }}
    podOverrides:
      metadata:
        labels:
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 10 }}
{{- end }}
    configOverrides:
      hive-site.xml:
        metastore.storage.schema.reader.impl: "org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader"
      hive-metastore-site.xml:
        metastore.storage.schema.reader.impl: "org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader"
    roleGroups:
      default:
        replicas: {{ .Values.nodes.metastore.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.metastore.cpu.max }}
              min: {{ .Values.nodes.metastore.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.metastore.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.metastore.memory }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              hive:
                console:
                  level: {{ .Values.nodes.metastore.logLevel }}
                file:
                  level: {{ .Values.nodes.metastore.logLevel }}
                loggers:
                  ROOT:
                    level: {{ .Values.nodes.metastore.logLevel }}
{{- end }}
