apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
    productVersion: {{ default .Chart.AppVersion .Values.stackProduct }}
    stackableVersion: {{ default "23.1.0" .Values.stackVersion }}
  hdfs:
    configMap: {{ .Values.hdfsClusterName }}
  clusterConfig:
    database:
      connString: jdbc:postgresql://{{ .Values.hiveDB.name }}/{{ .Values.hiveDB.db}}
      user: {{ .Values.hiveDB.user }}
      password: {{ .Values.hiveDB.password }}
      dbType: postgres
  metastore:
    configOverrides:
      hive-site.xml:
        metastore.storage.schema.reader.impl: "org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader"
      hive-metastore-site.xml:
        metastore.storage.schema.reader.impl: "org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader"
    roleGroups:
      default:
        replicas: {{ .Values.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.metastore.cpu.max }}
              min: {{ .Values.metastore.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.metastore.storage.capacity }}
            memory:
              limit: {{ .Values.metastore.memory }}
