apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: {{ include "hive-metastore.name" . }}
spec:
  version: {{ default .Chart.AppVersion .Values.stackTag }}
  metastore:
    roleGroups:
      default:
        replicas: {{ .Values.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.metastore.cpu.max }}
              min: {{ .Values.metastore.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.metastore.storage.capacity }}
            memory:
              limit: {{ .Values.metastore.memory }}
          # Volumes disabled until clarifications on possibility is in
          #volumeMounts:
          #- name: hive-env
          #  mountPath: /stackable/spark/conf
          #- name: hadoop-env
          #  mountPath: /etc/hadoop/conf
          database:
            connString: jdbc:postgresql://hive-postgres-postgresql/hive
            user: test-user
            password: test-password
            dbType: postgres
    # Volumes disabled until clarifications on possibility is in
    #volumes:
    #- name: hive-env
    #  configMap:
    #    name: {{ include "hive-metastore.name" . }}-hive-env
    #- name: hadoop-env
    #  configMap:
    #    name: {{ .Values.hdfsClusterName }}
