apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
    productVersion: {{ default .Chart.AppVersion .Values.stackProduct }}
    stackableVersion: {{ default "23.1.0" .Values.stackVersion }}
  clusterConfig:
    hdfsConfigMapName: {{ .Values.hdfsClusterName }}
    zookeeperConfigMapName: {{ .Values.zookeeperClusterName }}-znode
  masters:
    configOverrides:
      hbase-site.xml:
        hbase.rootdir: {{ .Values.hbaseRootDirectory }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.master.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.master.cpu.max }}
              min: {{ .Values.nodes.master.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.master.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.master.memory }}
  regionServers:
    configOverrides:
      hbase-site.xml:
        hbase.rootdir: {{ .Values.hbaseRootDirectory }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.region.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.region.cpu.max }}
              min: {{ .Values.nodes.region.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.region.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.region.memory }}
  restServers:
    roleGroups:
      default:
        replicas: {{ .Values.nodes.rest.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.rest.cpu.max }}
              min: {{ .Values.nodes.rest.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.rest.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.rest.memory }}