apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  image:
{{ include "gbif-chart-lib.stackableImage" . | indent 4 }}
  clusterConfig:
    hdfsConfigMapName: {{ .Values.hdfs.clusterName }}
    zookeeperConfigMapName: {{ .Values.zookeeper.clusterName }}-znode
    listenerClass: {{ .Values.listenerClass }}
{{- if .Values.logging.enabled  }}     
    vectorAggregatorConfigMapName: {{ .Values.logging.discoveryMap }}
{{- end }}
  masters:
{{- if .Values.yunikorn.enabled }}
    podOverrides:
      metadata:
        labels:
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 10 }}
{{- end }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.master.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.master.cpu.max }}
              min: {{ .Values.nodes.master.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.master.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.master.memory }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              hbase:
                console:
                  level: {{ .Values.nodes.master.logLevel }}
                file:
                  level: {{ .Values.nodes.master.logLevel }}
                loggers:
                  ROOT:
                    level: {{ .Values.nodes.master.logLevel }}
{{- end }}
{{- if (or .Values.nodes.master.nodeAffinity .Values.nodes.master.podAntiAffinity)}}
          affinity:
{{- with .Values.nodes.master.nodeAffinity }}
            nodeAffinity:
{{- toYaml . | nindent 14 }}
{{- end }}
{{- with .Values.nodes.master.podAntiAffinity }}
            podAntiAffinity:
{{- toYaml . | nindent 14 }}
{{- end }}
{{- end }}
{{- if .Values.configOverrides }}
{{- "configOverrides:" | nindent 8 }}
{{- tpl (.Values.configOverrides | toYaml) . | nindent 10 }}
{{- end }}
  regionServers:
{{- if .Values.yunikorn.enabled }}
    podOverrides:
      metadata:
        labels:
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 10 }}
{{- end }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.region.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.region.cpu.max }}
              min: {{ .Values.nodes.region.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.region.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.region.memory }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              hbase:
                console:
                  level: {{ .Values.nodes.region.logLevel }}
                file:
                  level: {{ .Values.nodes.region.logLevel }}
                loggers:
                  ROOT:
                    level: {{ .Values.nodes.region.logLevel }}
{{- end }}
{{- if (or .Values.nodes.region.nodeAffinity .Values.nodes.region.podAntiAffinity)}}
          affinity:
{{- with .Values.nodes.region.nodeAffinity }}
            nodeAffinity:
{{- toYaml . | nindent 14 }}
{{- end }}
{{- with .Values.nodes.region.podAntiAffinity }}
            podAntiAffinity:
{{- toYaml . | nindent 14 }}
{{- end }}
{{- end }}
{{- if .Values.configOverrides }}
{{- "configOverrides:" | nindent 8 }}
{{- tpl (.Values.configOverrides | toYaml) . | nindent 10 }}
{{- end }}
  restServers:
{{- if .Values.yunikorn.enabled }}
    podOverrides:
      metadata:
        labels:
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 10 }}
{{- end }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.rest.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.rest.cpu.max }}
              min: {{ .Values.nodes.rest.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.rest.storage.capacity }}
            memory:
              limit: {{ .Values.nodes.rest.memory }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              hbase:
                console:
                  level: {{ .Values.nodes.rest.logLevel }}
                file:
                  level: {{ .Values.nodes.rest.logLevel }}
                loggers:
                  ROOT:
                    level: {{ .Values.nodes.rest.logLevel }}
{{- end }}
{{- if .Values.configOverrides }}
{{- "configOverrides:" | nindent 8 }}
{{- tpl (.Values.configOverrides | toYaml) . | nindent 10 }}
{{- end }}