# Default values for GBIF Hive metastore using Stackable hive operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable tag to override the version of the Stack component.
stackTag: ""

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

# BUG Trino can't connect to hive cluster with more than 1 replicas
replicas: 1

metastore:
  cpu:
    min: '100m'
    max: '4000m'
  memory: '4Gi'
  storage:
    capacity: '10Gi'