# Default values for GBIF HDFS cluster using Stackable HDFS operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "403"
stackVersion: "23.1.0"

# Name of the hive metastore
hiveMetastoreName: "gbif-hive-metastore"

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

# Name of catalog used in GBIF
catalog: "gbif"

# limit for per-node usage for queries
memPerNode: "5GB"
# limit for headroom per node
# headroom + limit per-node shouldn't exceed the total memory set per worker.
memHeadroom: "1GB"

#GBIF specified nodeports for exposing the infrastructure to VMs outside the kubenetes cluster
appPort: 9083
nodePort: 31908

nodes:
  coordinator:
    replicas: 1
    cpu:
      min: '100m'
      max: '2000m'
    memory: '2Gi'
    storage:
      capacity: '4Gi'
  worker:
    replicas: 6
    cpu:
      min: '100m'
      max: '6000m'
    memory: '8Gi'
    storage:
      capacity: '8Gi'
  
nodeSelector: {}