# Default values for GBIF Spark application for process data and prepare map tiles.
# Name of the application, chart uses the name to find the .jar file.
appName: "spark-generate-maps"
# Repository and tag for finding the image if selfhosted.
image:
  repository: ""
  tag: ""

# Stackable tag to use for the Spark application.
stackTag: 3.4.0-stackable23.7.0
# Spark running mode, currently only cluster is supported.
mode: cluster
# Main class for starting the Spark process.
appClass: org.gbif.maps.workflow.Backfill

# Ressource configuration for spark driver.
driver:
  # Number of cores for the Spark driver.
  core: '2000m'
  # Memory for the Spark driver.
  mem: '2Gi'

# Ressource configuration for spark executors.
executor:
  # Number of cores for each executor.
  core: '2000m'
  # Memory for each executor.
  mem: '2Gi'
  # Number of executors.
  instances: 1

nameOverride: ""
fullnameOverride: ""

#Mode for installing. This is a implemtantion for selecting which objects to install.
## all: Installs both spark application and configmaps - will fail if configmap already exists
## config: Installs the configmaps maps into a namespace
## app: Installs the spark application
# The use case is for enabling templating only the application for use in Airflows or start an instance of spark within necessary updating the configsmaps
installMode: config

hdfs:
  # Name of the Stackabl HdfsCluster in the namespace.
  clusterName: hdfs
  # Directory of the snapshot location, needs to be created beforehand in the HDFS cluster.
  snapshotDir: data/hdfsview/occurrence/
  # Source directory of the data loaded into the HDFS cluster.
  sourceSubDir: occurrence/
  # Target directory for the produced HFiles from the Spark application. Currently needs to be cleaned afeter each run.
  targetDir: hfiles/dev_maps
  # Space in zookeeper to place the lock
  namespace: dev_index_lock
  # Path to place the lock
  lockPath: /hive/
  # Lock name
  lockName: hdfsview
  # Timeout time for each try, set in ms.
  sleepMs: 100
  # Number of retries
  retries: 5

map:
  # Number of minimum entries before it is created as a tile
  tileThreshold: 1000
  # Tile buffer size
  tileBuffer: 64
  # Tile size
  tileSize: 512
  # zoom levels goes from 0 up to limit underneath
  zoom: 16

hive:
  # Name of the hive cluster
  clusterName: hive-metastore
  # Name of the hive database
  schema: dev

hbase:
  # Name of the hbase cluster
  clusterName: hbase
  # Table name in HBase, needs to be created first with the correct number of regions
  tableName: dev_maps
  # Modulus for doing the salts in hbase
  saltModulus: 10