# Default values for GBIF Hive metastore using Stackable hive operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "3.1.3"
stackVersion: "23.1.0"

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

# BUG Trino can't connect to hive cluster with more than 1 replicas
replicas: 1

# Using more than 1 replica or using a different default service naming scheme, set the thrift url manually
thriftUrl: ""

# Use for setting the warehouse location
warehouse: "/gbif/warehouse"

#Values for setting ports to something different than default
appPort: 9083
nodePort: 31083

metastore:
  cpu:
    min: '100m'
    max: '4000m'
  memory: '4Gi'
  storage:
    capacity: '10Gi'

# Connection to Hive's postgres DB
hiveDB:
  db: ""
  name: ""
  user: ""
  password: ""