# Default values for GBIF Hive metastore using Stackable hive operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "3.1.3"
stackVersion: "23.7.0"

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

# Using more than 1 replica or using a different default service naming scheme, set the thrift url manually
thriftUrl: ""

# Use for setting the warehouse location
warehouse: "/gbif/warehouse"

# Enable logging via the vector aggregator
# Needs the name of configmap for discovery of the aggregator
logging:
  # property for enable vector logging
  enabled: false
  # DisoveryMap for the connection the aggregator pod
  discoveryMap: "gbif-vector-aggregator-discovery"
  # Configured which vector itself logs on its own.
  vectorLogLevel: "WARN"

nodes:
  metastore:
    replicas: 1
    cpu:
      min: '100m'
      max: '4000m'
    memory: '4Gi'
    storage:
      capacity: '10Gi'
    logLevel: "INFO"

# Connection to Hive's postgres DB
hiveDB:
  db: ""
  name: ""
  user: ""
  password: ""