{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  ingressClassName: nginx
  rules:
  - host: yunikorn.{{ .Values.ingress.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: {{ include "gbif-chart-lib.name" . }}-service
            port:
              number: {{ .Values.ingress.port }}
{{- end }}