apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gbif-chart-lib.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "gbif-chart-lib.name" . }}-account
  namespace: {{ .Release.Namespace }}