apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - "spark.stackable.tech"
  resources:
  - pods
  - pods/log
  - pods/exec
  - configmaps
  - persistentvolumeclaims
  - services
  - sparkapplications
  - events
  - status
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection