apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "gbif-chart-lib.name" . }}-account
type: kubernetes.io/service-account-token