apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-account
  namespace: {{ .Release.Namespace }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gbif-spark-sa
  namespace: {{ .Release.Namespace }}