apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-{{ .Release.Namespace }}-tls
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: {{ include "gbif-chart-lib.name" . }}-{{ .Release.Namespace }}-tls-ca
          namespace: {{ .Release.Namespace }}
        autoGenerate: true
        caCertificateLifetime: {{ .Values.caLifetime }}
      maxCertificateLifetime: {{ .Values.maxCertLifetime }}