{{- if or (eq (lower .Values.installMode) "all") (eq (lower .Values.installMode) "config")  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-conf
data:
  config.yml: |
    hdfsLock:
      zkConnectionString: {{ .Values.zookeeper.quorum }}
      namespace: dev_index_lock
      path: /hive/
      name: hdfsview
      connectionSleepTimeMs: 100
      connectionMaxRetries: 3
    hiveDatabase: downloads
    tablePartitions: 200
    sourceDirectory: /data/hdfsview/
    targetDirectory: /hive/
    usePartitionedTable: true
    coreName: occurrence
    tableName: occurrence_new
    warehouseLocation: /stackable/warehouse
    hiveThriftAddress: {{ .Values.hive.thrift }}
{{- end }}