# Default values for GBIF airflow cluster using Stackable airflow operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable tag to override the version of the Stack component.
stackTag: ""

# Executor airflow should use
executor: CeleryExecutor

# Version of statsd exporter to use
statsdVersion: 0.22.4

# Should load examples
examples: false

# Expose configs
exposeConfigs: false

#Admin user for Airflow
admin:
  firstName: ""
  lastName: ""
  email: ""
  user: ""
  password: ""
  secret: ""

#Database information for Airflows state database
airflowDB:
  name: ""
  user: ""
  pass: ""
  db: airflow

#Redis information for Airflows queue system
airflowRedis:
  name: airflow-redis
  pass: ""

nodes:
  webservers:
    replicas: '1'
    cpu:
      min: '100m'
      max: '2000m'
    memory: '4Gi'
  workers:
    replicas: '3'
    cpu:
      min: '100m'
      max: '3000m'
    memory: '8Gi'
  schedulers:
    replicas: '1'
    cpu:
      min: '100m'
      max: '1000m'
    memory: '2Gi'

storageCapacity: '2Gi'

airflowEnvOverrides:
  AIRFLOW__CORE__DAGS_FOLDER: "/gbif/airflow/dags"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/gbif/airflow/plugins"
  AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER: "True"
  AIRFLOW_CONN_KUBERNETES_IN_CLUSTER: "kubernetes://?__extra__=%7B%22extra__kubernetes__in_cluster%22%3A+true%2C+%22extra__kubernetes__kube_config%22%3A+%22%22%2C+%22extra__kubernetes__kube_config_path%22%3A+%22%22%2C+%22extra__kubernetes__namespace%22%3A+%22%22%7D"