apiVersion: v1
kind: Secret
metadata:
  name: gbif-superset-credentials
type: Opaque
stringData:
  adminUser.username: 
  adminUser.firstname: 
  adminUser.lastname: 
  adminUser.email: 
  adminUser.password: 
  connections.secretKey: 
  connections.sqlalchemyDatabaseUri: 