apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-credentials
type: Opaque
stringData:
  adminUser.username: {{ .Values.admin.user }}
  adminUser.firstname: {{ .Values.firstname }}
  adminUser.lastname: {{ .Values.lastname }}
  adminUser.email: {{ .Values.email }}
  adminUser.password: {{ .Values.password }}
  connections.secretKey: {{ .Values.secretSalt }}
  connections.sqlalchemyDatabaseUri: postgresql://{{ .Values.supersetDB.user }}:{{ .Values.supersetDB.pass }}@{{ .Values.supersetDB.host }}/{{ .Values.supersetDB.databaseName }}