apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Chart.AppVersion | default "8.5.3" | quote }}
  # Currently disabled tls on the http port to make it easier to connect vector
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  # Setting Elastic to read secrets for fileRealm if they exists in the values files
  {{- if or .Values.customUsers .Values.customRoles }}
  auth:
  {{- if .Values.customUsers }}
    fileRealm:
  {{- range $index, $value := .Values.customUsers }}
    - secretName: {{ include "gbif-chart-lib.name" $ }}-user-{{ $index }} 
  {{- end }}
  {{- end }}
   {{- if .Values.customUsers }}
    roles:
  {{- range $index, $value := .Values.customRoles }}
    - secretName: {{ include "gbif-chart-lib.name" $ }}-role-{{ $index }} 
  {{- end }}
  {{- end }}
  {{- end }}
  nodeSets:
  - name: managers
    count: {{ .Values.nodes.manager.replicas }}
    config:
      node:
        store:
          allow_mmap: {{ .Values.memoryPagingAllow }}
        roles: ["master"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            runAsUser: 1000 # Sets to the gbif user
          env:
          - name: ES_JAVA_OPTS
            value: -Xms{{ sub .Values.nodes.manager.resources.memory 512 }}m -Xmx{{ sub .Values.nodes.manager.resources.memory 512 }}m
          resources:
            requests:
              memory: {{ .Values.nodes.manager.resources.memory }}Mi
              cpu: {{ .Values.nodes.manager.resources.cpu.min }}
            limits:
              memory: {{ .Values.nodes.manager.resources.memory }}Mi
              cpu: {{ .Values.nodes.manager.resources.cpu.max }}
{{- if (or .Values.nodes.manager.nodeAffinity .Values.nodes.manager.podAntiAffinity)}}
      affinity:
{{- with .Values.nodes.manager.nodeAffinity }}
        nodeAffinity:
{{- toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.nodes.manager.podAntiAffinity }}
        podAntiAffinity:
{{- toYaml . | nindent 10 }}
{{- end }}
{{- end }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Points to standard mount directory
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.nodes.manager.resources.storage.capacity }}
        storageClassName: {{ $.Values.nodes.manager.resources.storage.class }}
  - name: workers
    count: {{ .Values.nodes.worker.replicas }}
    config:
      node:
        store:
          allow_mmap: {{ .Values.memoryPagingAllow }}
        roles: ["data", "ingest", "transform"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            runAsUser: 1000 # Sets to the gbif user
          env:
          - name: ES_JAVA_OPTS
            value: -Xms{{ sub .Values.nodes.worker.resources.memory 1024 }}m -Xmx{{ sub .Values.nodes.worker.resources.memory 1024 }}m
          resources:
            requests:
              memory: {{ .Values.nodes.worker.resources.memory }}Mi
              cpu: {{ .Values.nodes.worker.resources.cpu.min }}
            limits:
              memory: {{ .Values.nodes.worker.resources.memory }}Mi
              cpu: {{ .Values.nodes.worker.resources.cpu.max }}
{{- if (or .Values.nodes.worker.nodeAffinity .Values.nodes.worker.podAntiAffinity)}}
      affinity:
{{- with .Values.nodes.worker.nodeAffinity }}
        nodeAffinity:
{{- toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.nodes.worker.podAntiAffinity }}
        podAntiAffinity:
{{- toYaml . | nindent 10 }}
{{- end }}
{{- end }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Points to standard mount directory
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.nodes.worker.resources.storage.capacity }}
        storageClassName: {{ $.Values.nodes.worker.resources.storage.class }}