apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ default "8.5.3" .Chart.AppVersion }}
  count: {{ .Values.nodes.kibana.replicas }}
  # Disables ssl for kibana as there is ssl termination enabled
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: {{ include "gbif-chart-lib.name" . }}
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: ES_JAVA_OPTS
          value: -Xms{{ sub .Values.nodes.kibana.resources.memory 512 }}m -Xmx{{ sub .Values.nodes.kibana.resources.memory 512 }}m
        resources:
          requests:
            memory: {{ .Values.nodes.kibana.resources.memory }}Mi
            cpu: {{ .Values.nodes.kibana.resources.cpu.min }}
          limits:
            memory: {{ .Values.nodes.kibana.resources.memory }}Mi
            cpu: {{ .Values.nodes.kibana.resources.cpu.max }}