{{- range $index, $role := .Values.customRoles }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "gbif-chart-lib.name" $ }}-role-{{ $index }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/opaque
stringData:
  roles.yml: |-
    {{ $role.name }}:
      run_as: [ ]
      cluster: [ 'monitor' ]
      indices:
      - names: [ {{ $role.indice }} ]
        privileges: [ {{ $role.privileges }} ]
      allow_restricted_indices: false
---
{{- end}}

{{- range $index, $user := .Values.customUsers }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "gbif-chart-lib.name" $ }}-user-{{ $index }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $user.name }}
  password: {{ $user.password }}
  roles: {{ $user.roles }}
---
{{- end}}