{{- range $index, $user := .Values.customUsers }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "gbif-chart-lib.name" $ }}-user-{{ $index }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $user.name }}
  password: {{ $user.password }}
  roles: {{ $user.roles }}
---
{{- end}}