apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  image:
{{ include "gbif-chart-lib.stackableImage" . | indent 4 }}
  clusterOperation:
    reconciliationPaused: {{ .Values.clusterOperation.reconciliationPaused }}
    stopped: {{ .Values.clusterOperation.stopped }}
  clusterConfig:
    listenerClass: {{ .Values.listenerClass }}
{{- if .Values.logging.enabled  }}     
    vectorAggregatorConfigMapName: {{ .Values.logging.discoveryMap }}
{{- end }}
  servers:
    configOverrides:
      zoo.cfg:
        maxClientCnxns: {{ .Values.client.maxConnections | quote }}
        minSessionTimeout: {{ .Values.client.minSessionTimeout | quote }}
        maxSessionTimeout: {{ .Values.client.maxSessionTimeout | quote }}
    podOverrides:
{{- if .Values.yunikorn.enabled }}
      metadata:
        labels:
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 10 }}
{{- end }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.server.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.server.cpu.max }}
              min: {{ .Values.nodes.server.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.server.storage }}
            memory:
              limit: {{ .Values.nodes.server.memory }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              zookeeper:
                console:
                  level: {{ .Values.nodes.server.logLevel }}
                file:
                  level: {{ .Values.nodes.server.logLevel }}
                loggers:
                  ROOT:
                    level: {{ .Values.nodes.server.logLevel }}
                  org.apache.zookeeper.server.NettyServerCnxn:
                    level: NONE
{{- end }}
{{- if (or .Values.nodes.server.nodeAffinity .Values.nodes.server.podAntiAffinity)}}
          affinity:
{{- with .Values.nodes.server.nodeAffinity }}
            nodeAffinity:
{{- toYaml . | nindent 14 }}
{{- end }}
{{- with .Values.nodes.server.podAntiAffinity }}
            podAntiAffinity:
{{- toYaml . | nindent 14 }}
{{- end }}
{{- end }}