apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
    productVersion: {{ default .Chart.AppVersion .Values.stackProduct }}
    stackableVersion: {{ default "23.1.0" .Values.stackVersion }}
  clusterConfig:
{{- if .Values.logging.enabled  }}     
    vectorAggregatorConfigMapName: {{ .Values.logging.discoveryMap }}
    databaseInitialization:
      logging:
        enableVectorAgent: true
{{- end }}
  servers:
    roleGroups:
      default:
        replicas: {{ .Values.nodes.server.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.nodes.server.resources.cpu.max }}
              min: {{ .Values.nodes.server.resources.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.nodes.server.resources.storage }}
            memory:
              limit: {{ .Values.nodes.server.resources.memory }}
          affinity:
            nodeAffinity: 
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: zookeeper
                    operator: In
                    values:
                    - enabled
