apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
    productVersion: {{ default .Chart.AppVersion .Values.stackProduct }}
    stackableVersion: {{ default "23.1.0" .Values.stackVersion }}
  servers:
    roleGroups:
      default:
        replicas: {{ .Values.replicas }}
        config:
          resources:
            cpu:
              max: {{ .Values.ressources.cpu.max }}
              min: {{ .Values.ressources.cpu.min }}
            storage:
              data:
                capacity: {{ .Values.ressources.storage }}
            memory:
              limit: {{ .Values.ressources.memory }}
