{{ range $n := until (len .Values.nodes.namenode.ips) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%d" $.Release.Name "name-local" $n }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-namenode-default-%d" ( include "gbif-chart-lib.name" $ ) $n }}
  ports:
  - name: gbif-tcp
    protocol: TCP
    port: {{ $.Values.nodes.namenode.tcpPort }}
    targetPort: {{ $.Values.nodes.namenode.tcpPort }}
  - name: gbif-rcp
    protocol: TCP
    port: {{ $.Values.nodes.namenode.rcpPort }}
    targetPort: {{ $.Values.nodes.namenode.rcpPort }}
  externalIPs: 
  - {{ (index $.Values.nodes.namenode.ips $n) }}
---
{{ end }}

{{ range $n := until (len .Values.nodes.datanode.ips) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%d" $.Release.Name "data-local" $n }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-datanode-default-%d" ( include "gbif-chart-lib.name" $ ) $n }}
  ports:
  - name: gbif-tcp
    protocol: TCP
    port: {{ $.Values.nodes.datanode.tcpPort }}
    targetPort: {{ $.Values.nodes.datanode.tcpPort }}
  - name: gbif-icp
    protocol: TCP
    port: {{ $.Values.nodes.datanode.icpPort }}
    targetPort: {{ $.Values.nodes.datanode.icpPort }}
  - name: gbif-data
    protocol: TCP
    port: {{ $.Values.nodes.datanode.dataPort }}
    targetPort: {{ $.Values.nodes.datanode.dataPort }}
  externalIPs: 
  - {{ (index $.Values.nodes.datanode.ips $n) }}
---
{{ end }}