{{- range $n := until (len .Values.nodes.namenode.ips) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%d" $.Release.Name "name-local" $n }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-namenode-default-%d" ( include "gbif-chart-lib.name" $ ) $n }}
  ports:
  - name: gbif-tcp
    protocol: TCP
    port: {{ $.Values.nodes.namenode.tcpPort }}
    targetPort: {{ $.Values.nodes.namenode.tcpPort }}
  - name: gbif-rcp
    protocol: TCP
    port: {{ $.Values.nodes.namenode.rcpPort }}
    targetPort: {{ $.Values.nodes.namenode.rcpPort }}
  externalIPs: 
  - {{ (index $.Values.nodes.namenode.ips $n) }}
---
{{- end }}

{{- range $datanodeKey, $datanodeValue := .Values.nodes.datanode.groups }}
{{- range $n := until (len $datanodeValue.ips) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%d" $datanodeKey "local-port" $n }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-datanode-%s-%d" ( include "gbif-chart-lib.name" $ ) $datanodeKey $n }}
  ports:
  - name: gbif-tcp
    protocol: TCP
    port: {{ $.Values.nodes.datanode.ports.tcpPort }}
    targetPort: {{ $.Values.nodes.datanode.ports.tcpPort }}
  - name: gbif-icp
    protocol: TCP
    port: {{ $.Values.nodes.datanode.ports.icpPort }}
    targetPort: {{ $.Values.nodes.datanode.ports.icpPort }}
  - name: gbif-data
    protocol: TCP
    port: {{ $.Values.nodes.datanode.ports.dataPort }}
    targetPort: {{ $.Values.nodes.datanode.ports.dataPort }}
  externalIPs: 
  - {{ (index $datanodeValue.ips $n) }}
---
{{- end }}
{{- end }}