{{- if gt (len .Values.nodes.datanode.storage.drives) 0 }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Values.nodes.datanode.storage.class }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}