# Default values for GBIF HDFS cluster using Stackable HDFS operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable tag to override the version of the Stack component.
stackTag: ""

# Name of the hive metastore
hiveMetastoreName: "gbif-hive-metastore"

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

# Name of catalog used in GBIF
catalog: "gbif"

nodes:
  coordinator:
    replicas: 1
    cpu:
      min: '100m'
      max: '2000m'
    memory: '2Gi'
    storage:
      capacity: '4Gi'

  worker:
    replicas: 6
    cpu:
      min: '100m'
      max: '8000m'
    memory: '12Gi'
    storage:
      capacity: '8Gi'
  
nodeSelector: {}