apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-auth
spec:
  provider:
    static:
      userCredentialsSecret:
        name: {{ include "gbif-chart-lib.name" . }}-users