apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "gbif-chart-lib.name" . }}-users
type: kubernetes.io/opaque
stringData:
{{- range $user, $pass := .Values.customUsers }}
  {{ $user }}: {{ $pass }}
{{- end}}
---
{{- if .Values.catalogs }}
{{if .Values.catalogs.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-trino-psql-user
stringData:
  user: {{ .Values.catalogs.postgresql.user }}
  password: {{ .Values.catalogs.postgresql.password }}
{{- end }}
{{- end }}