apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "gbif-chart-lib.name" . }}-users
type: kubernetes.io/opaque
stringData:
{{- range $user, $pass := .Values.customUsers }}
  {{ $user }}: {{ $pass }}
{{- end}}