apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
{{- if .Values.customImage }}
    productVersion: "{{ .Values.stackProduct }}"
    custom: {{ .Values.customImage.repository }}/{{ .Values.customImage.image }}:{{ .Values.customImage.tag }}
{{- else }}
    productVersion: {{ default .Chart.AppVersion .Values.stackProduct }}
    stackableVersion: {{ default "23.1.0" .Values.stackVersion }}
{{- end }}
  clusterConfig:
{{- if .Values.logging.enabled  }}     
    vectorAggregatorConfigMapName: {{ .Values.logging.discoveryMap }}
{{- end }}
    authentication:
    - authenticationClass: {{ include "gbif-chart-lib.name" . }}-auth
    catalogLabelSelector:
      matchLabels:
{{ include "gbif-chart-lib.selectorLabels" . | indent 8}}
  coordinators:
    roleGroups:
      default:
        replicas: {{ .Values.nodes.coordinator.replicas }}
        config:
          resources:
            cpu:
              min: {{ .Values.nodes.coordinator.cpu.min }}
              max: {{ .Values.nodes.coordinator.cpu.max }}
            memory:
              limit: {{ .Values.nodes.coordinator.memory }}
            storage:
              data:
                capacity: {{ .Values.nodes.coordinator.storage.capacity }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              trino:
                console:
                  level: {{ .Values.nodes.coordinator.logLevel }}
                file:
                  level: {{ .Values.nodes.coordinator.logLevel }}
                loggers:
                  io.trino:
                    level: {{ .Values.nodes.coordinator.logLevel }}
{{- end }}
{{- if .Values.persistedGeocodeLayerStorage.enabled }}
        podOverrides:
          spec:
            containers:
            - name: trino
              volumeMounts:
              - name: gbif-geocode-layers
                mountPath: /gbif/geocode-layers
            volumes:
            - name: gbif-geocode-layers
              persistentVolumeClaim:
                claimName: {{ include "gbif-chart-lib.name" .}}-geocode-layers
                readOnly: false
{{- end }}
  workers:
    configOverrides:
      config.properties:
        query.max-memory-per-node: {{ .Values.memPerNode }}
        memory.heap-headroom-per-node: {{ .Values.memHeadroom }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.worker.replicas }}
        config:
          resources:
            cpu:
              min: {{ .Values.nodes.worker.cpu.min }}
              max: {{ .Values.nodes.worker.cpu.max }}
            memory:
              limit: {{ .Values.nodes.worker.memory }}
            storage:
              data:
                capacity: {{ .Values.nodes.worker.storage.capacity }}
{{- if .Values.logging.enabled  }}
          logging:
            enableVectorAgent: true
            containers:
              vector:
                file:
                  level: {{ .Values.logging.vectorLogLevel }}
              trino:
                console:
                  level: {{ .Values.nodes.worker.logLevel }}
                file:
                  level: {{ .Values.nodes.worker.logLevel }}
                loggers:
                  io.trino:
                    level: {{ .Values.nodes.worker.logLevel }}
{{- end }}
{{- if .Values.persistedGeocodeLayerStorage.enabled }}
        podOverrides:
          spec:
            containers:
            - name: trino
              volumeMounts:
              - name: gbif-geocode-layers
                mountPath: /gbif/geocode-layers
            volumes:
            - name: gbif-geocode-layers
              persistentVolumeClaim:
                claimName: {{ include "gbif-chart-lib.name" .}}-geocode-layers
                readOnly: true
{{- end }}