apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  image:
    productVersion: {{ default .Chart.AppVersion .Values.stackProduct | quote }}
    stackableVersion: {{ default "23.1.0" .Values.stackVersion }}
  catalogLabelSelector:
    matchLabels:
{{ include "gbif-chart-lib.selectorLabels" . | indent 6}}
  coordinators:
    roleGroups:
      default:
        replicas: {{ .Values.nodes.coordinator.replicas }}
        config:
          resources:
            cpu:
              min: {{ .Values.nodes.coordinator.cpu.min }}
              max: {{ .Values.nodes.coordinator.cpu.max }}
            memory:
              limit: {{ .Values.nodes.coordinator.memory }}
            storage:
              data:
                capacity: {{ .Values.nodes.coordinator.storage.capacity }}
  workers:
    configOverrides:
      config.properties:
        query.max-memory-per-node: {{ .Values.memPerNode }}
        memory.heap-headroom-per-node: {{ .Values.memHeadroom }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.worker.replicas }}
        config:
          resources:
            cpu:
              min: {{ .Values.nodes.worker.cpu.min }}
              max: {{ .Values.nodes.worker.cpu.max }}
            memory:
              limit: {{ .Values.nodes.worker.memory }}
            storage:
              data:
                capacity: {{ .Values.nodes.worker.storage.capacity }}