apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vectortile-server.fullname" . }}
  labels:
    {{- include "vectortile-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vectortile-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vectortile-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: application-config
              mountPath: /app/application.yml
              subPath: application.yml
            - name: bootstrap-config
              mountPath: /app/bootstrap.yml
              subPath: bootstrap.yml           
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: application-config
          configMap:
            name: {{ include "vectortile-server.name" . }}-configuration
            items:
              - key: application.yml
                path: application.yml
        - name: bootstrap-config
          configMap:
            name: {{ include "vectortile-server.name" . }}-bootstrap
            items:
              - key: bootstrap.yml
                path: bootstrap.yml