# Default values for GBIF HDFS cluster using Stackable HDFS operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable tag to override the version of the Stack component.
stackProduct: "2.4.12"
stackVersion: "23.7.0"

# Name of the zookeeper cluster
zookeeperClusterName: "gbif-zookeeper"

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

# hbase root folder for storing data
hbaseRootDirectory: /hbase

nodes:
  master:
    replicas: 1
    cpu:
      min: '100m'
      max: '2000m'
    memory: '4Gi'
    storage:
      capacity: '4Gi'
    # Currently no support in the service template for external ip ports for master node
    ips: []
  region:
    replicas: 3
    cpu:
      min: '100m'
      max: '3000m'
    memory: '8Gi'
    storage:
      capacity: '16Gi'
    tcpPort: 16020
    # List of IPs hosting the specific nodes.
    # Example server1 host region2 and server2 host region1
    # Then it should look like:
    # ips:
    #  - server2_ip
    #  - server1_ip
    ips: []
  rest:
    replicas: 1
    cpu:
      min: '100m'
      max: '1000m'
    memory: '2Gi'
    storage:
      capacity: '2Gi'
    # Currently no support in the service template for external ip ports for rest node
    ips: []