{{- if or (eq (lower .Values.installMode) "all") (eq (lower .Values.installMode) "config")  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-configuration
data:
  occurrence-table-backfill.yml: |
    hdfsLock:
      zkConnectionString: {{ .Values.zookeeper.quotum }}
      namespace: dev_index_lock
      path: /hive/
      name: hdfsview
      connectionSleepTimeMs: 100
      connectionMaxRetries: 3
    hiveDatabase: downloads
    tablePartitions: 200
    sourceDirectory: /data/hdfsview/
    targetDirectory: /data/hive/
    usePartitionedTable: true
    coreName: occurrence
    tableName: dev2_occurrence
    warehouseLocation: /stackable/warehouse
    hiveThriftAddress: {{ .Values.hive.thrift }}
{{- end }}