# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

memoryPagingAllow: true

nodes:
  manager:
    replicas: 1
    resources:
      cpu:
        min: '500m'
        max: '2000m'
      memory: 3072
      storage:
        class: local-path
        capacity: '25Gi'
    #GBIF specified nodeports for exposing the infrastructure to VMs outside the kubenetes cluster
    ports:
      tcp:
        appPort: 9200
        nodePort: 31920
  worker:
    replicas: 1
    resources:
      cpu:
        min: '1000m'
        max: '4000m'
      memory: 4096
      storage:
        drives: []
        labels: []
        class: elastic-storage
        capacity: '100Gi'
    ports: {}
  kibana:
    replicas: 1
    resources:
      cpu:
        min: '500m'
        max: '2000m'
      memory: 2048
    ports: {}