# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

memoryPagingAllow: true

#GBIF specified nodeports for exposing the infrastructure to VMs outside the kubenetes cluster
appPort: 9200
nodePort: 31920

nodes:
  manager:
    replicas: 3
    cpu:
      min: '500m'
      max: '2000m'
    memory: 3072
    storage:
      class: local-path
      capacity: '25Gi'
  worker:
    replicas: 3
    cpu:
      min: '1000m'
      max: '4000m'
    memory: 4096
    storage:
      drives: []
      labels: []
      class: elastic-storage
      capacity: '100Gi'
  kibana:
    replicas: 1
    cpu:
      min: '500m'
      max: '2000m'
    memory: 2048