# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

memoryPagingAllow: true

# users that should be created for the cluster at cluster creation time
# example of who it could look:
# customUsers:
# - name: test1
#   password: test1Password
#   roles: "a_role"
# - name: test2
#   password: test2Password
#   roles: "another_role"

customUsers: []

nodes:
  manager:
    replicas: 1
    resources:
      cpu:
        min: '500m'
        max: '2000m'
      memory: 3072
      storage:
        class: local-path
        capacity: '25Gi'
    ports: {}
  worker:
    replicas: 1
    resources:
      cpu:
        min: '1000m'
        max: '4000m'
      memory: 4096
      storage:
        drives: []
        labels: []
        class: elastic-storage
        capacity: '100Gi'
    ports: {}
  kibana:
    replicas: 1
    resources:
      cpu:
        min: '500m'
        max: '2000m'
      memory: 2048
    ports: {}