apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ default .Chart.Name .Values.overrideName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ default .Chart.Name .Values.overrideName }}
  namespace: {{ .Release.Namespace }}