apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default .Chart.Name .Values.overrideName }}-pod-template
data:
  pod-template.yaml: |
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: spark-executor
        env:
          - name: SPARK_CONF_DIR
            value: /stackable/spark/conf
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop/conf
        volumeMounts:
          - mountPath: /etc/hadoop/conf/core-site.xml
            name: hadoop-env
            subPath: core-site.xml
          - mountPath: /etc/hadoop/conf/hdfs-site.xml
            name: hadoop-env
            subPath: hdfs-site.xml
          - mountPath: /etc/hadoop/conf/hive-site.xml
            name: hive-env
            subPath: hive-site.xml
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: hadoop-env
          configMap:
            name: {{ .Values.hdfs.clusterId }}
            items:
              - key: core-site.xml
                path: core-site.xml
              - key: hdfs-site.xml
                path: hdfs-site.xml
        - name: hive-env
          configMap:
            name: {{ .Values.hive.clusterId }}-custom
            items:
              - key: hive-site.xml
                path: hive-site.xml