apiVersion: v1
kind: Service
metadata:
  name: {{ include "gbif-chart-lib.releaseName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.label }}
  ports:
{{- if .Values.nodes.client.ports }}
{{- range $port := .Values.nodes.client.ports }}
  - name: {{ include "gbif-chart-lib.releaseName" $ }}-{{ $port.name }}
    protocol: TCP
    port: {{ $port.value }}
{{- end }}
{{- end }}