apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.label }}
  ports:
    - name: {{ default .Chart.Name .Values.overrideName }}
      protocol: TCP
      port: {{ .Values.ports.standard }}
    - name: {{ default .Chart.Name .Values.overrideName }}-blockmanager
      protocol: TCP
      port: {{ .Values.ports.blockmanager }}
    - name: {{ default .Chart.Name .Values.overrideName }}-ui
      protocol: TCP
      port: {{ .Values.ports.ui }}