apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
spec:
  version: {{ default .Chart.AppVersion .Values.stackTag }}
  statsdExporterVersion: v{{ .Values.statsdVersion }}
  executor: {{ .Values.executor }}
  loadExamples: {{ .Values.examples }}
  exposeConfig: {{ .Values.exposeConfigs }}
  credentialsSecret: {{ include "gbif-chart-lib.name" . }}-credentials
  volumes:
    - name: external-dags
      persistentVolumeClaim:
        claimName: {{ include "gbif-chart-lib.name" .}}-dag
        readOnly: true
  volumeMounts:
    - name: external-dags
      mountPath: {{ .Values.externalData }}
  webservers:
    roleGroups:
      default:
{{- if .Values.airflowEnvOverrides }}
{{- "envOverrides:" | nindent 8 }}
{{- tpl (.Values.airflowEnvOverrides | toYaml) . | nindent 10 }}
{{- end }}
        replicas: {{ .Values.nodes.webservers.replicas }}
  workers:
    roleGroups:
      default:
{{- if .Values.airflowEnvOverrides }}
{{- "envOverrides:" | nindent 8 }}
{{- tpl (.Values.airflowEnvOverrides | toYaml) . | nindent 10 }}
{{- end }}
        replicas: {{ .Values.nodes.workers.replicas }}
  schedulers:
    roleGroups:
      default:
{{- if .Values.airflowEnvOverrides }}
{{- "envOverrides:" | nindent 8 }}
{{- tpl (.Values.airflowEnvOverrides | toYaml) . | nindent 10 }}
{{- end }}
        replicas: {{ .Values.nodes.schedulers.replicas }}