apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-spark-clusterrole
rules:
- apiGroups:
  - spark.stackable.tech
  - ""
  resources:
  - sparkapplications
  - pods
  verbs:
  - create
  - get
  - list
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - pods/exec
  verbs:
  - create
  - get
  - list
  - delete