apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - spark.stackable.tech
  - ""
  resources:
  - sparkapplications
  - pods
  verbs:
  - create
  - get
  - list
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - pods/exec
  - configmaps
  verbs:
  - create
  - get
  - list
  - delete