apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gbif-chart-lib.name" . }}-role
subjects:
- kind: ServiceAccount
  name: airflow-serviceaccount
  namespace: {{ .Release.Namespace }}
