apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - spark.stackable.tech
  resources:
  - sparkapplications
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - pods/exec
  - configmaps
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - job
  verbs:
  - create
  - get
  - list
  - delete