{{- if .Values.git.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-gitsync
type: Opaque
stringData:
  user: {{ .Values.git.auth.name | required ".Values.git.auth.name is required." }}
  password: {{ .Values.git.auth.token | required ".Values.git.auth.token is required." }}
{{- end }}