apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  adminUser.username: {{ .Values.admin.user }}
  adminUser.firstname: {{ .Values.admin.firstName }}
  adminUser.lastname: {{ .Values.admin.lastName }}
  adminUser.email: {{ .Values.admin.email }}
  adminUser.password: {{ .Values.admin.password }}
  connections.secretKey: {{ .Values.admin.secret }}
  connections.sqlalchemyDatabaseUri: postgresql+psycopg2://{{ .Values.airflowDB.user }}:{{ .Values.airflowDB.pass }}@{{ .Values.airflowDB.name }}/{{ .Values.airflowDB.db }}
  connections.celeryResultBackend: db+postgresql://{{ .Values.airflowDB.user }}:{{ .Values.airflowDB.pass }}@{{ .Values.airflowDB.name }}/{{ .Values.airflowDB.db }}
  connections.celeryBrokerUrl: redis://:{{ .Values.airflowRedis.pass }}@{{ .Values.airflowRedis.name }}-master/0