# Default values for GBIF HDFS cluster using Stackable HDFS operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "3.3.4"
stackVersion: "0.3.0"

# Name of the zookeeper cluster
zookeeperClusterName: "gbif-zookeeper"

# Number of times data should be replicated in the HDFS cluster
dataReplication: 2

nodes:
  name:
    replicas: 2
    cpu:
      min: '100m'
      max: '2000m'
    memory: '3Gi'
    storage:
      capacity: '15Gi'
  data:
    replicas: 4
    cpu:
      min: '100m'
      max: '1000m'
    memory: '2Gi'
    storage:
      drives:
        - data_volume_1
        - data_volume_2
        - data_volume_3
        - data_volume_4
        - data_volume_5
        - data_volume_6
        - data_volume_7
        - data_volume_8
      labels:
        - datanode-1
        - datanode-2
        - datanode-3
        - datanode-4
      class: hdfs-datanode-storage
      capacity: '925Gi'
      type: "Disk"
  journal:
    replicas: 3
    cpu:
      min: '100m'
      max: '2000m'
    memory: '2Gi'
    storage:
      capacity: '15Gi'