apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: {{ .Values.catalog }}
  labels:
{{ include "gbif-chart-lib.selectorLabels" . | indent 4}}
spec:
  connector:
    hive:
      metastore:
        configMap: {{ .Values.hiveMetastoreName }}
      hdfs:
        configMap: {{ .Values.hdfsClusterName }}
