# Default values for GBIF HDFS cluster using Stackable HDFS operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable tag to override the version of the Stack component.
stackTag: ""

# Name of the zookeeper cluster
zookeeperClusterName: "gbif-zookeeper"

# Name of the HDFS cluster
hdfsClusterName: "gbif-hdfs"

nodes:
  master:
    replicas: 1
    cpu:
      min: '100m'
      max: '2000m'
    memory: '4Gi'
    storage:
      capacity: '4Gi'
  region:
    replicas: 3
    cpu:
      min: '100m'
      max: '3000m'
    memory: '8Gi'
    storage:
      capacity: '16Gi'
  rest:
    replicas: 1
    cpu:
      min: '100m'
      max: '1000m'
    memory: '2Gi'
    storage:
      capacity: '2Gi'