{{- if or (eq (lower .Values.installMode) "all") (eq (lower .Values.installMode) "config")  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-conf
data:
  config.properties: |
    hiveDB={{ .Values.hive.hiveDB }}
    sourceTable={{ .Values.sourceTable }}
    hiveTablePrefix={{ .Values.hive.hiveTablePrefix }}
    hbaseTable={{ .Values.hbase.table }}
    hbaseRegions={{ .Values.hbase.regions }}
    hbaseZK={{ .Values.ZK }}
    targetDir={{ .Values.targetDir }}
    hashCountThreshold={{ .Values.hashCountThreshold }}
{{- end }}
