repositories:
  - name: stackable-stable
    url: https://repo.stackable.tech/repository/helm-stable/
  - name: stackable-dev
    url: https://repo.stackable.tech/repository/helm-dev/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami/

releases:
- name: commons-operator
  namespace: stackable-operators
  chart: stackable-stable/commons-operator
  version: 0.3.0
  installed: true
  atomic: true
  wait: true
  hooks: 
  - events: ["postuninstall"]
    showlogs: true
    command: "./scripts/clean_crd.sh"
- name: secret-operator
  namespace: stackable-operators
  chart: stackable-stable/secret-operator
  version: 0.5.0
  installed: true
  atomic: true
  wait: true
  #Validation disabled since helmfile tries to validate the k8 object before CRD in common-operator is installed
  disableValidationOnInstall: true
  needs:
  - commons-operator
- name: hive-postgres
  namespace: stack-demo
  chart: bitnami/postgresql
  version: 12.0.0
  installed: true
  atomic: true
  wait: true
  # Remember to set the auth node values when running the helmfile.
  values:
  - image:
      tag: 10.22.0-debian-11-r36
  set: 
  - name: 'global.postgresql.auth.postgresPassword'
    value: test-password
- name: zookeeper-operator
  namespace: stackable-operators
  chart: stackable-stable/zookeeper-operator
  version: 0.11.0
  installed: true
  atomic: true
  needs:
  - secret-operator
- name: hdfs-operator
  namespace: stackable-operators
  chart: stackable-stable/hdfs-operator
  version: 0.5.0
  installed: true
  atomic: true
  needs:
  - secret-operator
- name: spark-k8s-operator
  namespace: stackable-operators
  chart: stackable-stable/spark-k8s-operator
  version: 0.5.0
  installed: true
  atomic: true
  needs:
  - secret-operator
- name: hbase-operator
  namespace: stackable-operators
  chart: stackable-stable/hbase-operator
  version: 0.4.0
  installed: true
  atomic: true
  needs:
  - hdfs-operator
- name: hive-operator
  namespace: stackable-operators
  chart: stackable-dev/hive-operator
  version: 0.8.0-nightly
  installed: true
  atomic: true
  needs:
  - hdfs-operator
- name: trino-operator
  namespace: stackable-operators
  chart: stackable-stable/trino-operator
  version: 0.7.0
  installed: true
  atomic: true
  needs:
  - hive-operator