{{/*
Manually configured nodeport services for the namenodes, 
as there might be support for setting fixed port in the future.
*/}}
{{ range $n := until (len .Values.nodePorts) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%d" $.Release.Name "nodeport" $n }}
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-%d" "gbif-hdfs-namenode-default" $n }}
  ports:
  - name: gbif-tcp
    protocol: TCP
    port: {{ (index $.Values.nodePorts $n).tcpPort }}
    targetPort: {{ (index $.Values.nodePorts $n).tcpPort }}
    nodePort: {{ (index $.Values.nodePorts $n).ntcpPort }}
  - name: gbif-rcp
    protocol: TCP
    port: {{ (index $.Values.nodePorts $n).rcpPort }}
    targetPort: {{ (index $.Values.nodePorts $n).rcpPort }}
    nodePort: {{ (index $.Values.nodePorts $n).nrcpPort }}
{{ end }}