apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  haproxy.cfg: |
      defaults
        mode http
        timeout connect 5000ms
        timeout client 5000ms
        timeout server 5000ms
        default-server maxconn 10

      frontend kube-controller-manager
        bind ${NODE_IP}:10257
        mode tcp
        default_backend kube-controller-manager

      backend kube-controller-manager
        mode tcp
        server kube-controller-manager 127.0.0.1:10257

      frontend kube-scheduler
        bind ${NODE_IP}:10259
        mode tcp
        default_backend kube-scheduler

      backend kube-scheduler
        mode tcp
        server kube-scheduler 127.0.0.1:10259

      frontend kube-proxy
        bind ${NODE_IP}:10249
        http-request deny if !{ path /metrics }
        default_backend kube-proxy

      backend kube-proxy
        server kube-proxy 127.0.0.1:10249

      frontend etcd
        bind ${NODE_IP}:2381
        http-request deny if !{ path /metrics }
        default_backend etcd

      backend etcd
        server etcd 127.0.0.1:2381