apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: metrics-proxy
  template:
    metadata:
      labels:
        app: metrics-proxy
{{- if .Values.yunikorn.enabled }}
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 8 }}
{{- end }}
    spec:
      containers:
      - name: haproxy
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.version}}
        resources:
          requests:
            cpu: {{ .Values.resources.cpu.request }}
            memory: {{ .Values.resources.memory.request }}
          limits:
            cpu: {{ .Values.resources.cpu.limit }}
            memory: {{ .Values.resources.memory.limit }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 99
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy
          name: config
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - configMap:
          name: {{ include "gbif-chart-lib.name" . }}-config
        name: config