# Default values for GBIF Zookeeper cluster using Stackable Zookeeper operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "3.8.1"
stackVersion: "23.7.0"

# Enable logging via the vector aggregator
# Needs the name of configmap for discovery of the aggregator
logging:
  # property for enable vector logging
  enabled: false
  # DisoveryMap for the connection the aggregator pod
  discoveryMap: "gbif-vector-aggregator-discovery"
  # Configured which vector itself logs on its own.
  vectorLogLevel: "WARN"

nodes:
  server:
    # Number of instances
    replicas: 3
    # CPU allocation in milicores for each instance
    cpu:
      min: '100m'
      max: '2000m'
    # Memory allocation for each instance
    memory: '4Gi'
    logLevel: 'INFO'
    # Storage allocation for each instance
    storage: '5Gi'
    #GBIF specified nodeports for exposing the infrastructure to VMs outside the kubenetes cluster
    ports:
      tcpPort: 2282
    # List of IPs hosting the specific nodes.
    # Example server1 host zookeeper2 and server2 host zookeeper1
    # Then it should look like:
    # ips:
    #  - server2_ip
    #  - server1_ip
    ips: []