# Default values for GBIF Zookeeper cluster using Stackable Zookeeper operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "3.8.0"
stackVersion: "23.1.0"

# Number of instances
replicas: 3

#GBIF specified nodeports for exposing the infrastructure to VMs outside the kubenetes cluster
appPort: 2282
nodePort: 31228

ressources:
  # CPU allocation in milicores for each instance
  cpu:
    min: '100m'
    max: '2000m'
  # Memory allocation for each instance
  memory: '4Gi'
  # Storage allocation for each instance
  storage: '5Gi'