apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-credentials
  labels:
    secrets.stackable.tech/class: {{ include "gbif-chart-lib.name" . }}-credentials-class 
stringData:
  accessKey: {{ .Values.bucket.connection.credentials.user }}
  secretKey: {{ .Values.bucket.connection.credentials.password }}