apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: {{ include "gbif-chart-lib.name" . }}-credentials-class 
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}