apiVersion: spark.stackable.tech/v1alpha1
kind: SparkHistoryServer
metadata:
  name: {{ include "gbif-chart-lib.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  image:
{{ include "gbif-chart-lib.stackableImage" . | indent 4 }}
  logFileDirectory:
    s3:
      prefix: {{ .Values.bucket.prefix }}
      bucket:
        inline:
          bucketName: {{ .Values.bucket.name }}
          connection:
            inline:
              host: {{ .Values.bucket.connection.host }}
              port: {{ .Values.bucket.connection.port }}
              accessStyle: Path
              credentials:
                secretClass: {{ include "gbif-chart-lib.name" . }}-{{ .Release.Namespace }}-credentials-class
{{- if .Values.sparkConf }}
  sparkConf:
{{- tpl (.Values.sparkConf | toYaml) . | nindent 4 }}
{{- end }}
  nodes:
{{- if .Values.yunikorn.enabled }}
    podOverrides:
      metadata:
        labels:
{{- include "gbif-chart-lib.yunikornLabels" . | nindent 10 }}
{{- end }}
    roleGroups:
      default:
        replicas: {{ .Values.nodes.historyServer.replicas }}
        config:
          cleaner: true
          resources:
            cpu:
              min: {{ .Values.nodes.historyServer.cpu.min }}
              max: {{ .Values.nodes.historyServer.cpu.max }}
            memory:
              limit: {{ .Values.nodes.historyServer.memory }}
