repositories:
  - name: stackable-stable
    url: https://repo.stackable.tech/repository/helm-stable/
  - name: stackable-dev
    url: https://repo.stackable.tech/repository/helm-dev/
  - name: eck-stable
    url: https://helm.elastic.co

releases:
- name: commons-operator
  namespace: stackable-system
  chart: stackable-stable/commons-operator
  version: 0.4.0
  installed: true
  atomic: true
  wait: true
  #hooks: 
  #- events: ["postuninstall"]
  #  showlogs: true
  #  command: "../scripts/clean_crd.sh"
- name: elastic-crds
  namespace: elastic-system
  chart: eck-stable/eck-operator-crds
  version: 2.5.0
  installed: true
  atomic: true
  wait: true
- name: secret-operator
  namespace: stackable-system
  chart: stackable-stable/secret-operator
  version: 0.6.0
  installed: true
  atomic: true
  wait: true
  #Validation disabled since helmfile tries to validate the k8 object before CRD in common-operator is installed
  disableValidationOnInstall: true
  needs:
  - commons-operator
- name: zookeeper-operator
  namespace: stackable-system
  chart: stackable-stable/zookeeper-operator
  version: 0.12.0
  installed: true
  atomic: true
  needs:
  - secret-operator
- name: hdfs-operator
  namespace: stackable-system
  chart: stackable-dev/hdfs-operator
  version: 0.7.0-nightly
  installed: true
  atomic: true
  needs:
  - secret-operator
- name: spark-k8s-operator
  namespace: stackable-system
  chart: stackable-stable/spark-k8s-operator
  version: 0.6.0
  installed: true
  atomic: true
  needs:
  - secret-operator
- name: hbase-operator
  namespace: stackable-system
  chart: stackable-stable/hbase-operator
  version: 0.5.0
  installed: true
  atomic: true
  needs:
  - hdfs-operator
- name: hive-operator
  namespace: stackable-system
  chart: stackable-stable/hive-operator
  version: 0.8.0
  installed: true
  atomic: true
  needs:
  - hdfs-operator
- name: trino-operator
  namespace: stackable-system
  chart: stackable-stable/trino-operator
  version: 0.8.0
  installed: true
  atomic: true
  needs:
  - hive-operator
- name: airflow-operator
  namespace: stackable-system
  chart: stackable-stable/airflow-operator
  version: 0.6.0
  installed: true
  atomic: true
  needs:
    - secret-operator
- name: elastic-operator
  namespace: elastic-system
  chart: eck-stable/eck-operator
  version: 2.5.0
  installed: true
  atomic: true
  needs:
    - elastic-crds
  values:
    - installCRDs: false
    - managedNameSpaces: '{gbif-develop}'
    - webhook.enabled: false
    - config.validateStorageClass: false