repositories:
  - name: stackable-stable
    url: https://repo.stackable.tech/repository/helm-stable/
  - name: stackable-dev
    url: https://repo.stackable.tech/repository/helm-dev/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts/
  - name: nginx-stable
    url: https://helm.nginx.com/stable/

releases:
- name: hive-postgres
  namespace: gbif-develop
  chart: bitnami/postgresql
  version: 12.1.6
  installed: true
  atomic: true
  wait: true

- name: airflow-postgres
  namespace: gbif-develop
  chart: bitnami/postgresql
  version: 11.9.13
  installed: true
  atomic: true
  wait: true

- name: airflow-redis
  namespace: gbif-develop
  chart: bitnami/redis
  version: 16.13.2
  installed: true
  atomic: true
  wait: true

- name: gbif-zookeeper
  namespace: gbif-develop
  chart: ../charts/gbif-zookeeper-cluster
  version: 0.1.0
  installed: true
  wait: true
  waitForJobs: true
- name: gbif-hadoop-hdfs
  namespace: gbif-develop
  version: 0.1.0
  chart: ../charts/gbif-hdfs-cluster
  installed: true
  wait: true
  waitForJobs: true
  needs:
    - gbif-zookeeper
- name: gbif-hbase
  namespace: gbif-develop
  version: 0.1.0
  chart: ../charts/gbif-hbase-cluster
  installed: true
  wait: true
  waitForJobs: true
  needs:
    - gbif-hadoop-hdfs
- name: gbif-hive
  namespace: gbif-develop
  version: 0.1.0
  chart: ../charts/gbif-hive-cluster
  installed: true
  wait: true
  waitForJobs: true
  needs:
    - gbif-hadoop-hdfs
    - hive-postgres

- name: gbif-trino
  namespace: gbif-develop
  version: 0.1.1
  chart: ../charts/gbif-trino-cluster
  installed: true
  wait: true
  waitForJobs: true
  needs:
    - gbif-hive
- name: gbif-airflow
  namespace: gbif-develop
  version: 0.1.1
  chart: ../charts/gbif-airflow-cluster
  installed: true
  wait: true
  waitForJobs: true
  needs:
    - airflow-postgres
    - airflow-redis
    - gbif-trino

- name: gbif-elastic
  namespace: gbif-develop
  version: 0.1.0
  chart: ../charts/gbif-elastic-cluster
  installed: true
  wait: true
  waitForJobs: true
