# Default values for GBIF airflow cluster using Stackable airflow operator.

# Override name of the cluster
nameOverride: ""
# Override fullname of the cluster
fullnameOverride: ""

# Stackable versioning to override the version of the Stack component.
stackProduct: "3.0.1"
stackVersion: "23.11.0"

# Uses the stackProduct value to tell the operator what version of configurations to use with the custom image
# custom image allows customer to change the repository if they want to their own acting as a proxy or
# use an extended version of the image
# Example of how to set custom image
# customImage: 
#  enabled: true
#  repository: docker.gbif.org/your-team
#  extended:
#    enabled: true
#    image: a-extended-stackable-image
#    tag: "1.0.5"
customImage: {}

# Admin user for Superset, will be created as a secret
admin:
  firstname: ""
  lastname: ""
  email: ""
  user: ""
  password: ""

# Unfathomable long string of random charecters
# Used to sign session cookies
secretSalt: ""

# Database information for Superset state database
supersetDB:
  host: ""
  user: ""
  pass: ""
  databaseName: superset

# Enable logging via the vector aggregator
# Needs the name of configmap for discovery of the aggregator
logging:
  # property for enable vector logging
  enabled: false
  # DisoveryMap for the connection the aggregator pod
  discoveryMap: "gbif-vector-aggregator-discovery"
  # Configured which vector itself logs on its own.
  vectorLogLevel: "WARN"

# ListenerClassName for Stackable to create the service from
exposure: cluster-internal

# Support for Yunikorn queuing
# By default it is disabled.
# The idea with enabling yunikorn for components is that we can fence the infrastructure components from works done in Spark, Trino etc.
yunikorn:
  enabled: false
  # Name of the overall application for all the pods within the queue
  appId: "superset"
  # Queue to place the pods in
  queue: "root.namespace.infra"

nodes:
  supersetnode:
    replicas: 1
    cpu:
      min: '250m'
      max: '2000m'
    memory: '2Gi'
    logLevel: "INFO"
    # Port for setting up node port given node - Leave empty to not setup port
    ports: {}

# Used to provide a custom defined set of superset configurations to overwrite.
# Currently works on role group level
supersetConfigOverride: {}

# Used to provide a custom defined set of envrionment variable to provide for superset pods
# Used across all the different role groups
supersetEnvOverride: {}