apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default .Chart.Name .Values.overrideName }}-hive
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>hive.metastore.uris</name>
        <value>{{ .Values.hive.thrift }}</value>
      </property>
    </configuration>