apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Chart.Name .Values.overrideName }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      serviceAccountName: {{ default .Chart.Name .Values.overrideName }}
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 100
      volumes:
        - name: {{ default .Chart.Name .Values.overrideName }}-pipeline
          configMap:
            name: {{ default .Chart.Name .Values.overrideName }}-pipeline
        - name: {{ default .Chart.Name .Values.overrideName }}-template
          configMap:
            name: {{ default .Chart.Name .Values.overrideName }}-template
        - name: {{ default .Chart.Name .Values.overrideName }}-kube
          configMap:
            name: {{ default .Chart.Name .Values.overrideName }}-kube
        - name: {{ default .Chart.Name .Values.overrideName }}-generic
          configMap:
            name: {{ default .Chart.Name .Values.overrideName }}-generic
        - name: {{ default .Chart.Name .Values.overrideName }}-core
          configMap:
            name: {{ .Values.hdfs.clusterId }}
            items:
            - key: core-site.xml
              path: core-site.xml
            - key: hdfs-site.xml
              path: hdfs-site.xml
        - name: {{ default .Chart.Name .Values.overrideName }}-hive
          configMap:
            name: {{ default .Chart.Name .Values.overrideName }}-hive
            items:
            - key: hive-site.xml
              path: hive-site.xml 
        - name: {{ default .Chart.Name .Values.overrideName }}-logback
          configMap:
            name: {{ default .Chart.Name .Values.overrideName }}-logback
      containers:
      - name: {{ default .Chart.Name .Values.overrideName }}-container
        image: {{.Values.product.repository}}/{{ .Values.product.artifact }}:{{ .Values.product.version }}
        resources:
          requests:
            memory: {{ .Values.resources.mem }}
            cpu: "100m"
          limits:
            memory: {{ .Values.resources.mem }}
            cpu: {{ .Values.resources.cpu }}
        command: {{ toJson .Values.command }}
        env:
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop/conf
        volumeMounts:
        - name: {{ default .Chart.Name .Values.overrideName }}-pipeline
          mountPath: /home/gbif/config/pipeline-configurations.yaml
          subPath: pipeline-configurations.yaml
        - name: {{ default .Chart.Name .Values.overrideName }}-core
          mountPath: /etc/hadoop/conf/core-site.xml
          subPath: core-site.xml
        - name: {{ default .Chart.Name .Values.overrideName }}-core
          mountPath: /etc/hadoop/conf/hdfs-site.xml
          subPath: hdfs-site.xml
        - name: {{ default .Chart.Name .Values.overrideName }}-hive
          mountPath: /etc/hadoop/conf/hive-site.xml
          subPath: hive-site.xml
        - name: {{ default .Chart.Name .Values.overrideName }}-logback
          mountPath: /home/gbif/config/pipelines-logback.xml
          subPath: pipelines-logback.xml
        - name: {{ default .Chart.Name .Values.overrideName }}-generic
          mountPath: /home/gbif/config/pipeline-generic.yaml
          subPath: pipeline-generic.yaml
        - name: {{ default .Chart.Name .Values.overrideName }}-template
          mountPath: /home/gbif/config/spark-template.yaml
          subPath: pod-template.yaml
        - name: {{ default .Chart.Name .Values.overrideName }}-kube
          mountPath: /home/gbif/config/kubeconfig.yaml
          subPath: kubeconfig.yaml
      dnsConfig:
        options:
        - name: ndots
          value: "7"